Game.LoadP3DFile("art\\missions\\level01\\sr3.p3d")
Game.LoadP3DFile("art\\missions\\level01\\race3cam.p3d")
Game.LoadP3DFile("art\\missions\\generic\\fline.p3d")
Game.LoadDisposableCar("art\\cars\\honor_v.p3d","honor_v","AI")
Game.LoadP3DFile( "art\\frontend\\dynaload\\images\\msnicons\\object\\race.p3d" )
